import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../core/bloc/dark_light_bloc/cubit.dart';
import '../../core/constants/dimensions.dart';
import '../../core/constants/icon_manager.dart';
import '../../core/router/router.dart';
import '../contact_us/form.dart';
import 'utils/details_container.dart';
import '../../widgets/custom_button.dart';
import '../../widgets/sliver_page.dart';
import '../../core/constants/color_manager.dart';
import '../../core/constants/image_manager.dart';
import '../../core/constants/strings.dart';
import '../../core/theme/fonts_style.dart';
import '../../widgets/custom_cached_image.dart';
import '../../widgets/review_item.dart';
import '../all_reviews_page/form.dart';
import '../book_service/form.dart';

part 'utils/consultant_name.dart';
part 'utils/description.dart';
part 'utils/book_button.dart';
part 'utils/consultant_image.dart';
part 'utils/reviews.dart';
part 'utils/question.dart';
part 'utils/services_containers.dart';

class ConsultantForm extends StatelessWidget {
  const ConsultantForm({super.key});

  @override
  Widget build(BuildContext context) {
    /// Will Replace with API Data
    List<String> icons = [
      IconManager.audio,
      IconManager.video,
      IconManager.chatFilled,
    ];

    List<String> services = [
      Strings.audioCall.tr(),
      Strings.videoCall.tr(),
      Strings.chat.tr(),
    ];
    ThemeState themeState = context.watch<ThemeCubit>().state;
    return Scaffold(
      body: Stack(
        children: [
          CustomSliverPage(
            image: const _ConsultantImage(),
            imageHeight: 240.h,
            body: Padding(
                padding: EdgeInsets.all(Dimensions.defaultPadding),
                child: Stack(
                  children: [
                    Column(
                      children: [
                        _ConsultantName(
                          name: context.locale.toString() == 'ar'
                              ? 'محمد احمد'
                              : 'Mohamed Ahmed',
                          specialty: context.locale.toString() == 'ar'
                              ? 'استشاري نفسي'
                              : 'Psychological Consultant',
                        ),
                        SizedBox(height: 20.h),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            DetailsContainer(
                              icon: IconManager.star,
                              subTitle: Strings.reviews.tr(),
                              title: '4.6',
                            ),
                            SizedBox(width: 5.w),
                            DetailsContainer(
                              icon: IconManager.person,
                              subTitle: Strings.consultations.tr(),
                              title: '+10',
                            ),
                            SizedBox(width: 5.w),
                            DetailsContainer(
                              icon: IconManager.check,
                              subTitle: Strings.experience.tr(),
                              title: '+3',
                            ),
                          ],
                        ),
                        SizedBox(height: 20.h),
                        Divider(
                          color: themeState == ThemeState.light
                              ? ColorManager.blackTextColor
                              : ColorManager.dividerColor,
                        ),
                        SizedBox(height: 20.h),
                        _Description(
                          description: context.locale.toString() == 'ar'
                              ? 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.'
                              : 'This is an example of text that can be replaced in the same space, this text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.',
                        ),
                        SizedBox(height: 20.h),
                        Divider(
                          color: themeState == ThemeState.light
                              ? ColorManager.blackTextColor
                              : ColorManager.dividerColor,
                        ),
                        SizedBox(height: 20.h),
                        // Top Questions
                        Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.start,
                              children: [
                                Text(
                                  Strings.frequentlyAskedQuestions.tr(),
                                  style: AppTextStyle.h1,
                                ),
                              ],
                            ),
                            SizedBox(height: 10.h),
                            _Question(
                              //  question about diabetes
                              question: context.locale.toString() == 'ar'
                                  ? 'ما هي اعراض مرض السكر؟'
                                  : 'What are the symptoms of diabetes?',
                            ),
                            SizedBox(height: 10.h),
                            _Question(
                              // question about liver
                              question: context.locale.toString() == 'ar'
                                  ? 'ما هي اعراض مرض الكبد؟'
                                  : 'What are the symptoms of liver disease?',
                            ),
                          ],
                        ),

                        SizedBox(height: 20.h),
                        Divider(
                          color: themeState == ThemeState.light
                              ? ColorManager.blackTextColor
                              : ColorManager.dividerColor,
                        ),
                        SizedBox(height: 20.h),
                        const _Reviews(),
                        SizedBox(height: 20.h),
                        Divider(
                          color: themeState == ThemeState.light
                              ? ColorManager.blackTextColor
                              : ColorManager.dividerColor,
                        ),
                        SizedBox(height: 20.h),

                        Column(
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.start,
                              children: [
                                Text(
                                  Strings.availableServices.tr(),
                                  style: AppTextStyle.h1,
                                ),
                              ],
                            ),
                            SizedBox(height: 20.h),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.start,
                              children: [
                                Text(
                                  Strings.quickQuestion.tr(),
                                  style: AppTextStyle.h1.copyWith(
                                    fontSize: 18.sp,
                                  ),
                                ),
                              ],
                            ),
                            // Description
                            SizedBox(height: 10.h),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.start,
                              children: [
                                Expanded(
                                  child: Text(
                                    Strings.quicklyAskATextQuestionAndChooseTheResponseFormatYouWant.tr(),
                                    style: AppTextStyle.h3.copyWith(
                                      color: ColorManager.greyTextColor,
                                      fontWeight: FontWeight.w400,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            SizedBox(height: 20.h),
                            const _Services(),

                            SizedBox(height: 50.h),



                          ],
                        ),

                        /////////////// Button
                        SizedBox(height: 60.h),
                      ],
                    ),
                  ],
                )),
          ),
          Positioned(
            bottom: 0.h,
            left: 0,
            right: 0,
            child: _BookButton(),
          ),
        ],
      ),
    );
  }
}

